	;HEATHKIT ET3400 MANUAL - PAGE 55 - SAMPLE 1
	;TURN ON AND OFF EACH SEGMENT IN
	;SEQUENCE BEGINNING AT H DISPLAY
	;USES MONITOR SUBROUTINES REDIS AND OUTCH
	;NOTE: ONE DP IN EACH DISPLAY IS ACTIVE

REDIS	= $FCBC
DIGADD	= $F0
OUTCH	= $FE3A

START	JSR REDIS	;SET UP FIRST DISPLAY ADDRESS
	LDAA #$01	;FIRST SEGMENT CODE
	BRA OUT
SAME	LDA B DIGADD	;FIX DISPLAY ADDRESS
	ADD B #$10	;FOR NEXT SEGMENT
	STA B DIGADD
	ASL A		;NEXT SEGMENT CODE
OUT	JSR OUTCH	;OUTPUT SEGMENT
	LDX #$2F00	;TIME TO WAIT
WAIT	DEX
	BNE WAIT	;TIME OUT YET?
	TAB
	TST B		;LAST SEGMENT THIS DISPLAY?
	BNE SAME	;NEXT SEGMENT
	LDA A #$01	;RESET SEGMENT CODE
	LDX DIGADD	;NEXT DISPLAY
	CPX #$C10F	;LAST DISPLAY YET?
	BNE OUT
	LDAA $10,X
	BRA START	;DO AGAIN
