	;HEATHKIT ET3400 MANUAL - PAGE 55 - SAMPLE 1
	;TURN ON AND OFF EACH SEGMENT IN
	;SEQUENCE BEGINNING AT H DISPLAY
	;USES MONITOR SUBROUTINES REDIS AND OUTCH
	;NOTE: ONE DP IN EACH DISPLAY IS ACTIVE

REDIS	= $FCBC
DIGADD	= $F0
OUTCH	= $FE3A

START	JSR REDIS	;SET UP FIRST DISPLAY ADDRESS
	LDA A #$01	;FIRST SEGMENT CODE
	BRA OUT
SAME	LDA B DIGADD+1	;FIX DISPLAY ADDRESS
	ADD B #$10	;FOR NEXT SEGMENT
	STA B DIGADD+1
	ASL A		;NEXT SEGMENT CODE